# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: README..*.md
      - id: end-of-file-fixer
        exclude: '(^\.devcontainer/devcontainer-lock\.json$)'
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=10240"]
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        # args: ['--baseline', '.secrets.baseline']
        # Exclude go test file and gitleaks config and any terraform.*.tfvars files in any directory
        exclude: '(.*_test.go|.gitleaks.toml|aqua-checksums.json|(?:^|/)(?:.*/)?terraform\.[^.]+\.tfvars$)'
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
  # --------------------------------------------------------------
  # For Shell Script
  # --------------------------------------------------------------
  - repo: https://github.com/cisagov/pre-commit-shfmt
    rev: v0.0.2
    hooks:
      - id: shfmt
        args:
          - -w
          - -i
          - "4"
          - -ci
          - -bn
          - -sr
  # --------------------------------------------------------------
  # For GitHub Actions
  # --------------------------------------------------------------
  - repo: local
    hooks:
      - id: actionlint
        name: actionlint
        description: GitHub Actions workflow linter.
        language: unsupported
        entry: actionlint -color=false
        types: [yaml]
        files: ^\.github/workflows/.*\.(ya?ml)$
  - repo: local
    hooks:
      - id: ghalint
        name: ghalint
        description: GitHub Actions workflow linter.
        language: unsupported
        entry: ghalint run --log-color never
        types: [yaml]
        files: ^\.github/workflows/.*\.(ya?ml)$
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.22.0 # https://github.com/zizmorcore/zizmor-pre-commit/releases
    hooks:
      # Run the linter.
      - id: zizmor
  # --------------------------------------------------------------
  # For Jsonnet
  # --------------------------------------------------------------
  # - repo: https://github.com/google/go-jsonnet
  #   rev: v0.21.0 # https://github.com/google/go-jsonnet/releases
  #   hooks:
  #     - id: jsonnet-format
  #     - id: jsonnet-lint
  # --------------------------------------------------------------
  # For Go
  # --------------------------------------------------------------
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go.
        entry: golangci-lint run --max-same-issues=0 --max-issues-per-linter=0 --config=.golangci.yaml --fix
        exclude: ^(.*_test.go|tmp/.*\.go)$
        language: golang
        pass_filenames: false
        types: [go]
  # --------------------------------------------------------------
  # For SQL
  # --------------------------------------------------------------
  # - repo: https://github.com/sqlfluff/sqlfluff
  #   rev: 4.0.4 # https://github.com/sqlfluff/sqlfluff/releases
  #   hooks:
  #     - id: sqlfluff-lint
  #       args: [--dialect, mysql]
  #     - id: sqlfluff-fix
  #       args: [--dialect, mysql]
  # --------------------------------------------------------------
  # For Terraform
  # --------------------------------------------------------------
  # - repo: https://github.com/antonbabenko/pre-commit-terraform
  #   rev: v1.105.0 # https://github.com/antonbabenko/pre-commit-terraform/releases
  #   hooks:
  #     - id: terraform_fmt
  #     - id: terraform_tflint
  #       args:
  #         - --args=-f=compact
  #         - --args=--chdir=/workspace/modules
  #         - --args=--no-color
  #         - --args=--call-module-type=all
  #     - id: terraform_trivy
  #       args:
  #         - --args=--format=table
  #         - --args=--skip-dirs="**/.terraform"
  #         - --args=--config="/workspace/trivy.yaml"
