# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        exclude: README.*.md
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=10240"]
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.4 # https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - --args=-f=compact
          - --args=--module
          - --args=--no-color
      # - id: terraform_trivy
      #   args:
      #     - --args=--format=table
      #     - --args=--skip-dirs="**/.terraform"

  # - repo: https://github.com/zricethezav/gitleaks
  #   rev: v7.6.0
  #   hooks:
  #     - id: gitleaks
