variable "deploy_user" {}
variable "tags" {}
variable "name_prefix" {}
variable "region" {}
variable "resourcegroups_group" {}
variable "budgets" {}
variable "health" {}
variable "trusted_advisor" {}
variable "iam" {}
variable "common_lambda" {}
variable "common_logging" {}
# security
variable "security_access_analyzer" {}
variable "security_cloudtrail" {}
variable "security_config" {}
variable "security_default_vpc" {}
variable "security_ebs" {}
variable "security_guardduty" {}
variable "security_iam" {}
variable "security_s3" {}
variable "security_securityhub" {}
