# https://help.github.com/ja/actions/reference/workflow-syntax-for-github-actions
name: cd-workflow-dispatch-base-dev
on:
  workflow_dispatch:
jobs:
  deploy:
    env:
      ENVIRONMENT: dev
      ENV: ${{ secrets.ENV_DEV }}
    runs-on: ubuntu-latest
    steps:
      - name: "code: check out code"
        uses: actions/checkout@v2
      - name: "terraform: apply"
        run: |
          echo "$ENV" >> $PWD/.env
          find scripts -type f -name '*.sh' -exec chmod +x \{\} \;
          docker pull ghcr.io/y-miyazaki/terraform-aws:latest
          docker run --rm -v $PWD:/workspace --env-file=$PWD/.env -w /workspace --name terraform-aws ghcr.io/y-miyazaki/terraform-aws:latest scripts/terraform/deploy.sh terraform/base
      - name: "slack: notification"
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_COLOR: "danger"
          SLACK_ICON: ""
          SLACK_TITLE: failed deploy on push
          SLACK_USERNAME: github-notification
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
