# https://help.github.com/ja/actions/reference/workflow-syntax-for-github-actions
name: deploy-workflow-dispatch-monitor-dev
on:
  workflow_dispatch:
jobs:
  deploy:
    env:
      ENVIRONMENT: dev
      ENV: ${{ secrets.ENV_DEV }}
      TERRAFORM_VERSION: 0.14.7
    runs-on: ubuntu-latest
    steps:
      - name: "code: check out code"
        uses: actions/checkout@v2
      - name: "terraform: apply"
        run: |
          echo "$ENV" >> $PWD/.env
          find scripts -type f -name '*.sh' -exec chmod +x \{\} \;
          docker pull ymiyazakixyz/terraform-aws:${{ env.TERRAFORM_VERSION }}
          docker run --rm -v $PWD:/workspace --env-file=$PWD/.env -w /workspace --name terraform-aws ymiyazakixyz/terraform-aws:${{ env.TERRAFORM_VERSION }} scripts/terraform/aws/deploy.sh terraform/monitor
      - name: "slack: notification"
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_COLOR: "danger"
          SLACK_ICON: ""
          SLACK_TITLE: failed deploy on push
          SLACK_USERNAME: github-notification
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
