# CD workflow: Build and deploy MkDocs to GitHub Pages
name: on-cd-mkdocs

run-name: "${{ github.workflow }} (${{ github.event_name }})"

on:
  push:
    branches:
      - "main"
    paths:
      - "docs/**"
      - "mkdocs.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    uses: y-miyazaki/config/.github/workflows/cd-mkdocs.yaml@e3e0b48915de1940dc92525eb66b6452775246c3 # v1.8.95
    with:
      artifact_name: mkdocs-site
      config_file: mkdocs.yml
      pip_packages: mkdocs-material mdx-truly-sane-lists
    permissions:
      contents: read

  deploy:
    needs: build
    uses: y-miyazaki/config/.github/workflows/cd-github-pages.yaml@e3e0b48915de1940dc92525eb66b6452775246c3 # v1.8.95
    with:
      artifact_name: mkdocs-site
    permissions:
      contents: read
      id-token: write
      pages: write
