# CI workflow for shell scripts
name: on-ci-push-script

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.sh"
      - ".github/workflows/on-ci-push-script.yaml"
      - ".github/workflows/ci-script.yaml"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.sh"
      - ".github/workflows/on-ci-push-script.yaml"
      - ".github/workflows/ci-script.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  script-ci:
    uses: y-miyazaki/config/.github/workflows/ci-script.yaml@a3b2e3c7c1f41e9a492f2ca372527c5143f6d65c # v1.0.0
    with:
      script_path: "**/*.sh"
    permissions:
      checks: write
      contents: read
      pull-requests: write
