# Manual workflow: ECS deployment (application, dev)
name: on-cd-wd-application-ecs-dev

run-name: "${{ github.workflow }} (${{ github.event_name }})"

on:
  workflow_dispatch: # Manual deployment workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  ecs-deploy:
    permissions:
      contents: read
      id-token: write
    uses: y-miyazaki/config/.github/workflows/cd-aws-ecs.yaml@f3ede5f3e6b4eab2392edef0c9b1912c2721174f # v1.8.98
    with:
      ecs_service_base_dir: "ecs/ecs-service/test-server"
      environment: "dev"
    secrets:
      AWS_IAM_ROLE_ARN: ${{ secrets.AWS_IAM_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
