# Manual workflow: ECS deployment (application, dev)
name: on-cd-wd-application-ecs-dev

run-name: "${{ github.workflow }} (${{ github.event_name }})"

on:
  workflow_dispatch: # Manual deployment workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  ecs-deploy:
    permissions:
      contents: read
      id-token: write
    uses: y-miyazaki/config/.github/workflows/cd-aws-ecs.yaml@d4fa362e4fae0121bd002e9487f3db3ca660a744 # v1.8.101
    with:
      ecs_service_base_dir: "ecs/ecs-service/test-server"
      environment: "dev"
    secrets:
      AWS_IAM_ROLE_ARN: ${{ secrets.AWS_IAM_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
