# CI workflow: Markdown lint on push/PR
name: on-ci-push-markdown

run-name: "${{ github.workflow }} (${{ github.event_name }})"

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.md"
      - "docs/**/*.md"
      - ".markdown-link-check.json"
      - ".markdownlint-cli2.yaml"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.md"
      - "docs/**/*.md"
      - ".markdown-link-check.json"
      - ".markdownlint-cli2.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  markdown-ci:
    uses: y-miyazaki/config/.github/workflows/ci-markdown.yaml@e3e0b48915de1940dc92525eb66b6452775246c3 # v1.8.95
    permissions:
      contents: read
      pull-requests: write
