# CI workflow: Node.js CI on push/PR
name: on-ci-push-nodejs

run-name: "${{ github.workflow }} (${{ github.event_name }})"

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "nodejs/**"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "nodejs/**"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  nodejs-ci:
    uses: y-miyazaki/config/.github/workflows/ci-nodejs.yaml@d4fa362e4fae0121bd002e9487f3db3ca660a744 # v1.8.101
    with:
      search_paths: nodejs
    permissions:
      contents: read
      id-token: write
      pull-requests: write
