# CD workflow: Build and deploy MkDocs to GitHub Pages
name: on-cd-mkdocs

on:
  push:
    branches:
      - "main"
    paths:
      - "docs/**"
      - "mkdocs.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    uses: y-miyazaki/config/.github/workflows/cd-mkdocs.yaml@8b07b501759bbe4716c759dfdbd914d4d5ebbdc3 # v1.8.59
    with:
      artifact_name: mkdocs-site
      config_file: mkdocs.yml
      pip_packages: mkdocs-material mdx-truly-sane-lists
    permissions:
      contents: read

  deploy:
    needs: build
    uses: y-miyazaki/config/.github/workflows/cd-github-pages.yaml@8b07b501759bbe4716c759dfdbd914d4d5ebbdc3 # v1.8.59
    with:
      artifact_name: mkdocs-site
    permissions:
      contents: read
      id-token: write
      pages: write
