# CI workflow for Markdown files
name: on-ci-push-markdown

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.md"
      - ".markdownlint.yaml"
      - ".github/workflows/on-ci-push-markdown.yaml"
      - ".github/workflows/ci-markdown.yaml"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.md"
      - ".markdownlint.yaml"
      - ".github/workflows/on-ci-push-markdown.yaml"
      - ".github/workflows/ci-markdown.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdown-ci:
    uses: y-miyazaki/config/.github/workflows/ci-markdown.yaml@6b09c1551e5376a4e2a8bca0356c182ecdfb454e # v1.0.1
    with:
      component: "base"
      environment: "markdown"
    permissions:
      contents: read
      pull-requests: write
