# CI workflow for shell scripts
name: on-ci-push-shell-script

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.sh"
      - ".github/workflows/on-ci-push-shell-script.yaml"
      - ".github/workflows/ci-shell-script.yaml"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.sh"
      - ".github/workflows/on-ci-push-shell-script.yaml"
      - ".github/workflows/ci-shell-script.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shell-script-ci:
    uses: y-miyazaki/config/.github/workflows/ci-shell-script.yaml@760cde0cc108082323466cbbf1d089019d75b513 # v1.0.3
    with:
      script_path: "**/*.sh"
    permissions:
      checks: write
      contents: read
      pull-requests: write
