# CI workflow: Node.js CI on push/PR
name: on-ci-push-nodejs

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "nodejs/**"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "nodejs/**"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  nodejs-ci:
    uses: y-miyazaki/config/.github/workflows/ci-nodejs.yaml@06f84d98a415f02750132aada0da639380d8b125 # v1.8.77
    with:
      search_paths: nodejs
    permissions:
      contents: read
      id-token: write
      pull-requests: write
