# CI workflow: Shell script lint on push/PR
name: on-ci-push-shell-script

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.sh"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.sh"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shell-script-ci:
    uses: y-miyazaki/config/.github/workflows/ci-shell-script.yaml@59f3fc2baeb78d374b3f0fdafeb1a07363af4b8c # v1.1.5
    with:
      script_path: "**/*.sh"
    permissions:
      checks: write
      contents: read
      pull-requests: write
