# Manual workflow: ECS deployment (application, dev)
name: on-cd-wd-application-ecs-dev

on:
  workflow_dispatch: # Manual deployment workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ecs-deploy:
    permissions:
      contents: read
      id-token: write
    uses: y-miyazaki/config/.github/workflows/cd-aws-ecs.yaml@ae434803ee16c58a449f5e1b925db1097687a556 # v1.0.8
    with:
      ecs_service_base_dir: "ecs/ecs-service/test-server"
      environment: "dev"
    secrets:
      AWS_IAM_ROLE_ARN: ${{ secrets.AWS_IAM_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
