# Deploy MkDocs documentation to GitHub Pages on push to main
name: on-cd-mkdocs

on:
  push:
    branches:
      - "main"
    paths:
      - "docs/**"
      - "mkdocs.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    permissions:
      contents: read
    uses: y-miyazaki/config/.github/workflows/cd-mkdocs.yaml@b92c65f70e5ed824c29ee4cd02e551da99c4d5e0 # v1.4.5
    with:
      artifact_name: mkdocs-site
      config_file: mkdocs.yml
      pip_packages: mkdocs-material mdx-truly-sane-lists

  deploy:
    needs: build
    permissions:
      contents: read
      id-token: write
      pages: write
    uses: y-miyazaki/config/.github/workflows/cd-github-pages.yaml@b92c65f70e5ed824c29ee4cd02e551da99c4d5e0 # v1.4.5
    with:
      artifact_name: mkdocs-site
