# CI workflow: Shell script lint on push/PR
name: on-ci-push-shell-script

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.sh"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.sh"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  shell-script-ci:
    uses: y-miyazaki/config/.github/workflows/ci-shell-script.yaml@cd498a0b7d7d69468d24398fa39daa87c767f76a # v1.1.37
    with:
      script_path: "**/*.sh"
    permissions:
      checks: write
      contents: read
      pull-requests: write
