# CI workflow: GitHub Actions workflow lint on push/PR
name: on-ci-push-github-actions-workflow

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"
      - ".github/actions/**/*.yml"
      - ".github/actions/**/*.yaml"
      - "**/action.yml"
      - "**/action.yaml"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"
      - ".github/actions/**/*.yml"
      - ".github/actions/**/*.yaml"
      - "**/action.yml"
      - "**/action.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  github-actions-workflow-ci:
    uses: y-miyazaki/config/.github/workflows/ci-github-actions-workflow.yaml@b92c65f70e5ed824c29ee4cd02e551da99c4d5e0 # v1.4.5
    permissions:
      contents: read
