variable "deploy_user" {}
variable "tags" {}
variable "name_prefix" {}
variable "region" {}
variable "common_lambda" {}
variable "common_log" {}
variable "delivery_log" {}
variable "metric_log_application" {}
variable "metric_log_postgres" {}
variable "metric_resource_alb" {}
variable "metric_resource_api_gateway" {}
variable "metric_resource_cloudfront" {}
variable "metric_resource_ec2" {}
variable "metric_resource_elasticache" {}
variable "metric_resource_lambda" {}
variable "metric_resource_rds" {}
variable "metric_resource_ses" {}
variable "metric_synthetics_canary" {}
variable "cloudwatch_event_ec2" {}
variable "synthetics_canary" {}
