# https://help.github.com/ja/actions/reference/workflow-syntax-for-github-actions
name: ci
on:
  - push
jobs:
  integration:
    env:
      ENVIRONMENT: example
      TERRAFORM_VERSION: 0.14.7
    runs-on: ubuntu-latest
    steps:
      - name: "code: check out code"
        uses: actions/checkout@v2
      - name: "parameters: set parameters"
        id: parameters
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "::set-output name=pr_number::${PR_NUMBER}"
      - name: "terraform: check"
        run: |
          docker pull ymiyazakixyz/terraform-aws:latest
          docker run --rm -v $PWD:/workspace -e ENV=${{ env.ENVIRONMENT }} -w /workspace --name terraform-aws ymiyazakixyz/terraform-aws:latest scripts/terraform/aws/integration_push.sh terraform
      - name: "slack: notification for failed build."
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_COLOR: "danger"
          SLACK_ICON: ""
          SLACK_TITLE: failed dev build(terraform-aws-base)
          SLACK_USERNAME: github-notification
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
