# https://help.github.com/ja/actions/reference/workflow-syntax-for-github-actions
name: ci-push
on:
  push:
    branches:
      - "feature/**"
      - "develop"
      - "master"
      - "main"
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: "code: check out code"
        uses: actions/checkout@v2
      - name: "parameters: set parameters"
        id: parameters
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "::set-output name=pr_number::${PR_NUMBER}"
      - name: "terraform: check"
        run: |
          echo "$ENV" >> $PWD/.env
          find scripts -type f -name '*.sh' -exec chmod +x \{\} \;
          docker pull ghcr.io/y-miyazaki/terraform-aws-debian:latest
          docker run --rm -v $PWD:/workspace --env-file=$PWD/.env -w /workspace --name terraform-aws ghcr.io/y-miyazaki/terraform-aws-debian:latest scripts/terraform/integration_push.sh terraform/base
          docker run --rm -v $PWD:/workspace --env-file=$PWD/.env -w /workspace --name terraform-aws ghcr.io/y-miyazaki/terraform-aws-debian:latest scripts/terraform/integration_push.sh terraform/monitor
      - name: "slack: notification for failed build."
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_COLOR: "danger"
          SLACK_ICON: ""
          SLACK_TITLE: failed dev build(terraform-aws-base)
          SLACK_USERNAME: github-notification
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
