# CI workflow: GitHub Actions workflow lint on push/PR
name: on-ci-push-github-actions-workflow

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"
      - ".github/actions/**/*.yml"
      - ".github/actions/**/*.yaml"
      - "**/action.yml"
      - "**/action.yaml"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"
      - ".github/actions/**/*.yml"
      - ".github/actions/**/*.yaml"
      - "**/action.yml"
      - "**/action.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  github-actions-workflow-ci:
    uses: y-miyazaki/config/.github/workflows/ci-github-actions-workflow.yaml@@237fbd05581748a6b74dc9cb2f354cadee6d5c88 # v1.1.3
    permissions:
      contents: read
