# CI workflow for shell scripts
name: on-ci-push-script

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.sh"
      - ".github/workflows/on-ci-push-script.yaml"
      - ".github/workflows/ci-script.yaml"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.sh"
      - ".github/workflows/on-ci-push-script.yaml"
      - ".github/workflows/ci-script.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  script-ci:
    uses: y-miyazaki/config/.github/workflows/ci-script.yaml@6b09c1551e5376a4e2a8bca0356c182ecdfb454e # v1.0.1
    with:
      script_path: "**/*.sh"
    permissions:
      checks: write
      contents: read
      pull-requests: write
