# CI workflow: Markdown lint on push/PR
name: on-ci-push-markdown

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.md"
      - "docs/**/*.md"
      - ".markdownlint.yaml"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.md"
      - "docs/**/*.md"
      - ".markdownlint.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdown-ci:
    uses: y-miyazaki/config/.github/workflows/ci-markdown.yaml@4d5104b3af3d62cc3afa960f5c9f99ae95699979 # v1.0.6
    permissions:
      contents: read
      pull-requests: write
    with:
      markdownlint_flags: "README*.md docs/**/*.md"
