# CI workflow for GitHub Actions workflows and actions
name: on-ci-push-github-actions-workflow

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"
      - ".github/actions/**/*.yml"
      - ".github/actions/**/*.yaml"
      - "**/action.yml"
      - "**/action.yaml"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"
      - ".github/actions/**/*.yml"
      - ".github/actions/**/*.yaml"
      - "**/action.yml"
      - "**/action.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  github-actions-workflow-ci:
    uses: y-miyazaki/config/.github/workflows/ci-github-actions-workflow.yaml@6b09c1551e5376a4e2a8bca0356c182ecdfb454e # v1.0.1
    permissions:
      contents: read
