# CI workflow: GitHub Actions workflow lint on push/PR
name: on-ci-push-github-actions-workflow

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"
      - ".github/actions/**/*.yml"
      - ".github/actions/**/*.yaml"
      - "**/action.yml"
      - "**/action.yaml"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"
      - ".github/actions/**/*.yml"
      - ".github/actions/**/*.yaml"
      - "**/action.yml"
      - "**/action.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  github-actions-workflow-ci:
    uses: y-miyazaki/config/.github/workflows/ci-github-actions-workflow.yaml@ae434803ee16c58a449f5e1b925db1097687a556 # v1.0.8
    permissions:
      contents: read
