# CI workflow for Markdown files
name: on-ci-push-markdown

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.md"
      - ".markdownlint.yaml"
      - ".github/workflows/on-ci-push-markdown.yaml"
      - ".github/workflows/ci-markdown.yaml"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.md"
      - ".markdownlint.yaml"
      - ".github/workflows/on-ci-push-markdown.yaml"
      - ".github/workflows/ci-markdown.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdown-ci:
    uses: y-miyazaki/config/.github/workflows/ci-markdown.yaml@a3b2e3c7c1f41e9a492f2ca372527c5143f6d65c # v1.0.0
    with:
      component: "base"
      environment: "markdown"
    permissions:
      contents: read
      pull-requests: write
